//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.17929
//     Generated on:    19/06/2013 11:04:07
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace IntelliScraper.Data {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class intelliScraper : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperSettings settingsField;
        
        /// <remarks/>
        public intelliScraperSettings settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
                this.RaisePropertyChanged("settings");
            }
        }
        
        /// <summary />
        private intelliScraperStoreInfo storeInfoField;
        
        /// <remarks/>
        public intelliScraperStoreInfo storeInfo {
            get {
                return this.storeInfoField;
            }
            set {
                this.storeInfoField = value;
                this.RaisePropertyChanged("storeInfo");
            }
        }
        
        /// <summary />
        private intelliScraperActionCollection actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public intelliScraperActionCollection Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettings : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool showInitialMessageField;
        
        /// <remarks/>
        public bool showInitialMessage {
            get {
                return this.showInitialMessageField;
            }
            set {
                this.showInitialMessageField = value;
                this.RaisePropertyChanged("showInitialMessage");
            }
        }
        
        /// <summary />
        private string initialMessageField;
        
        /// <remarks/>
        public string initialMessage {
            get {
                return this.initialMessageField;
            }
            set {
                this.initialMessageField = value;
                this.RaisePropertyChanged("initialMessage");
            }
        }
        
        /// <summary />
        private bool logIscraperInfoField;
        
        /// <remarks/>
        public bool logIscraperInfo {
            get {
                return this.logIscraperInfoField;
            }
            set {
                this.logIscraperInfoField = value;
                this.RaisePropertyChanged("logIscraperInfo");
            }
        }
        
        /// <summary />
        private bool useProxyField;
        
        /// <remarks/>
        public bool useProxy {
            get {
                return this.useProxyField;
            }
            set {
                this.useProxyField = value;
                this.RaisePropertyChanged("useProxy");
            }
        }
        
        /// <summary />
        private string proxyFileField;
        
        /// <remarks/>
        public string proxyFile {
            get {
                return this.proxyFileField;
            }
            set {
                this.proxyFileField = value;
                this.RaisePropertyChanged("proxyFile");
            }
        }
        
        /// <summary />
        private string userAgentField;
        
        /// <remarks/>
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("userAgent");
            }
        }
        
        /// <summary />
        private bool useCustomUserAgentFileListField;
        
        /// <remarks/>
        public bool useCustomUserAgentFileList {
            get {
                return this.useCustomUserAgentFileListField;
            }
            set {
                this.useCustomUserAgentFileListField = value;
                this.RaisePropertyChanged("useCustomUserAgentFileList");
            }
        }
        
        /// <summary />
        private string customUserAgentFileField;
        
        /// <remarks/>
        public string customUserAgentFile {
            get {
                return this.customUserAgentFileField;
            }
            set {
                this.customUserAgentFileField = value;
                this.RaisePropertyChanged("customUserAgentFile");
            }
        }
        
        /// <summary />
        private httpHeadersCollection globalHttpHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("globalHttpHeader")]
        public httpHeadersCollection globalHttpHeader {
            get {
                return this.globalHttpHeaderField;
            }
            set {
                this.globalHttpHeaderField = value;
                this.RaisePropertyChanged("globalHttpHeader");
            }
        }
        
        /// <summary />
        private int waitEachRequestMillisecondsField;
        
        /// <remarks/>
        public int waitEachRequestMilliseconds {
            get {
                return this.waitEachRequestMillisecondsField;
            }
            set {
                this.waitEachRequestMillisecondsField = value;
                this.RaisePropertyChanged("waitEachRequestMilliseconds");
            }
        }
        
        /// <summary />
        private int waitAfterErrorField;
        
        /// <remarks/>
        public int waitAfterError {
            get {
                return this.waitAfterErrorField;
            }
            set {
                this.waitAfterErrorField = value;
                this.RaisePropertyChanged("waitAfterError");
            }
        }
        
        /// <summary />
        private intelliScraperSettingsOnError onErrorField;
        
        /// <remarks/>
        public intelliScraperSettingsOnError onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
                this.RaisePropertyChanged("onError");
            }
        }
        
        /// <summary />
        private string imageFolderDownloadField;
        
        /// <remarks/>
        public string imageFolderDownload {
            get {
                return this.imageFolderDownloadField;
            }
            set {
                this.imageFolderDownloadField = value;
                this.RaisePropertyChanged("imageFolderDownload");
            }
        }
        
        /// <summary />
        private bool usePageLoopField;
        
        /// <remarks/>
        public bool usePageLoop {
            get {
                return this.usePageLoopField;
            }
            set {
                this.usePageLoopField = value;
                this.RaisePropertyChanged("usePageLoop");
            }
        }
        
        /// <summary />
        private intelliScraperSettingsPageLoopInfo pageLoopInfoField;
        
        /// <remarks/>
        public intelliScraperSettingsPageLoopInfo pageLoopInfo {
            get {
                return this.pageLoopInfoField;
            }
            set {
                this.pageLoopInfoField = value;
                this.RaisePropertyChanged("pageLoopInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class httpHeaders : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class SaveEntity : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool enableSaveField;
        
        /// <remarks/>
        public bool enableSave {
            get {
                return this.enableSaveField;
            }
            set {
                this.enableSaveField = value;
                this.RaisePropertyChanged("enableSave");
            }
        }
        
        /// <summary />
        private SaveEntityInputType inputTypeField;
        
        /// <remarks/>
        public SaveEntityInputType inputType {
            get {
                return this.inputTypeField;
            }
            set {
                this.inputTypeField = value;
                this.RaisePropertyChanged("inputType");
            }
        }
        
        /// <summary />
        private string tableNameField;
        
        /// <remarks/>
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("tableName");
            }
        }
        
        /// <summary />
        private SaveEntityMapCollection mappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("map", IsNullable=false)]
        public SaveEntityMapCollection mapping {
            get {
                return this.mappingField;
            }
            set {
                this.mappingField = value;
                this.RaisePropertyChanged("mapping");
            }
        }
        
        /// <summary />
        private bool checkExistField;
        
        /// <remarks/>
        public bool checkExist {
            get {
                return this.checkExistField;
            }
            set {
                this.checkExistField = value;
                this.RaisePropertyChanged("checkExist");
            }
        }
        
        /// <summary />
        private string checkExistAttributesField;
        
        /// <remarks/>
        public string checkExistAttributes {
            get {
                return this.checkExistAttributesField;
            }
            set {
                this.checkExistAttributesField = value;
                this.RaisePropertyChanged("checkExistAttributes");
            }
        }
        
        /// <summary />
        private SaveEntityIfExist ifExistField;
        
        /// <remarks/>
        public SaveEntityIfExist ifExist {
            get {
                return this.ifExistField;
            }
            set {
                this.ifExistField = value;
                this.RaisePropertyChanged("ifExist");
            }
        }
        
        /// <summary />
        private SaveEntityOnError onErrorField;
        
        /// <remarks/>
        public SaveEntityOnError onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
                this.RaisePropertyChanged("onError");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SaveEntityInputType {
        
        /// <remarks/>
        xpathSingle,
        
        /// <remarks/>
        xpathMultipleData,
        
        /// <remarks/>
        xpathDataChildrenList,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SaveEntityMap : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string mapColNameField;
        
        /// <remarks/>
        public string mapColName {
            get {
                return this.mapColNameField;
            }
            set {
                this.mapColNameField = value;
                this.RaisePropertyChanged("mapColName");
            }
        }
        
        /// <summary />
        private string refIdField;
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
                this.RaisePropertyChanged("refId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SaveEntityIfExist {
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        delete,
        
        /// <remarks/>
        stopAll,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SaveEntityOnError {
        
        /// <remarks/>
        log,
        
        /// <remarks/>
        stopAll,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class xpathEntity : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string idField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <summary />
        private string descriptionField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <summary />
        private string inputRuleIdField;
        
        /// <remarks/>
        public string inputRuleId {
            get {
                return this.inputRuleIdField;
            }
            set {
                this.inputRuleIdField = value;
                this.RaisePropertyChanged("inputRuleId");
            }
        }
        
        /// <summary />
        private string urlField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <summary />
        private string xpathField;
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private string attributeNameField;
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <summary />
        private object fetchedDataField;
        
        /// <remarks/>
        public object fetchedData {
            get {
                return this.fetchedDataField;
            }
            set {
                this.fetchedDataField = value;
                this.RaisePropertyChanged("fetchedData");
            }
        }
        
        /// <summary />
        private ResultActionEntityCollection postProcessDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postProcessData")]
        public ResultActionEntityCollection postProcessData {
            get {
                return this.postProcessDataField;
            }
            set {
                this.postProcessDataField = value;
                this.RaisePropertyChanged("postProcessData");
            }
        }
        
        /// <summary />
        private xpathEntityGetType getTypeField;
        
        /// <remarks/>
        public xpathEntityGetType getType {
            get {
                return this.getTypeField;
            }
            set {
                this.getTypeField = value;
                this.RaisePropertyChanged("getType");
            }
        }
        
        /// <summary />
        private xpathEntityFindType findTypeField;
        
        /// <remarks/>
        public xpathEntityFindType FindType {
            get {
                return this.findTypeField;
            }
            set {
                this.findTypeField = value;
                this.RaisePropertyChanged("FindType");
            }
        }
        
        /// <summary />
        private xpathEntityInputCollectionType inputCollectionTypeField;
        
        /// <remarks/>
        public xpathEntityInputCollectionType inputCollectionType {
            get {
                return this.inputCollectionTypeField;
            }
            set {
                this.inputCollectionTypeField = value;
                this.RaisePropertyChanged("inputCollectionType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ResultActionEntity : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private ResultActionEntitySubstringType substringTypeField;
        
        /// <remarks/>
        public ResultActionEntitySubstringType substringType {
            get {
                return this.substringTypeField;
            }
            set {
                this.substringTypeField = value;
                this.RaisePropertyChanged("substringType");
            }
        }
        
        /// <summary />
        private bool makeSubstringField;
        
        /// <remarks/>
        public bool makeSubstring {
            get {
                return this.makeSubstringField;
            }
            set {
                this.makeSubstringField = value;
                this.RaisePropertyChanged("makeSubstring");
            }
        }
        
        /// <summary />
        private int substringField;
        
        /// <remarks/>
        public int substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
                this.RaisePropertyChanged("substring");
            }
        }
        
        /// <summary />
        private int substringFromField;
        
        /// <remarks/>
        public int substringFrom {
            get {
                return this.substringFromField;
            }
            set {
                this.substringFromField = value;
                this.RaisePropertyChanged("substringFrom");
            }
        }
        
        /// <summary />
        private int substringToField;
        
        /// <remarks/>
        public int substringTo {
            get {
                return this.substringToField;
            }
            set {
                this.substringToField = value;
                this.RaisePropertyChanged("substringTo");
            }
        }
        
        /// <summary />
        private string substringSearchField;
        
        /// <remarks/>
        public string substringSearch {
            get {
                return this.substringSearchField;
            }
            set {
                this.substringSearchField = value;
                this.RaisePropertyChanged("substringSearch");
            }
        }
        
        /// <summary />
        private bool startWithEnabledField;
        
        /// <remarks/>
        public bool startWithEnabled {
            get {
                return this.startWithEnabledField;
            }
            set {
                this.startWithEnabledField = value;
                this.RaisePropertyChanged("startWithEnabled");
            }
        }
        
        /// <summary />
        private string startWithValField;
        
        /// <remarks/>
        public string startWithVal {
            get {
                return this.startWithValField;
            }
            set {
                this.startWithValField = value;
                this.RaisePropertyChanged("startWithVal");
            }
        }
        
        /// <summary />
        private string startWithAddValField;
        
        /// <remarks/>
        public string startWithAddVal {
            get {
                return this.startWithAddValField;
            }
            set {
                this.startWithAddValField = value;
                this.RaisePropertyChanged("startWithAddVal");
            }
        }
        
        /// <summary />
        private attachTypeEntity startWithAttachTypeField;
        
        /// <remarks/>
        public attachTypeEntity startWithAttachType {
            get {
                return this.startWithAttachTypeField;
            }
            set {
                this.startWithAttachTypeField = value;
                this.RaisePropertyChanged("startWithAttachType");
            }
        }
        
        /// <summary />
        private bool endWithEnabledField;
        
        /// <remarks/>
        public bool endWithEnabled {
            get {
                return this.endWithEnabledField;
            }
            set {
                this.endWithEnabledField = value;
                this.RaisePropertyChanged("endWithEnabled");
            }
        }
        
        /// <summary />
        private string endWithValField;
        
        /// <remarks/>
        public string endWithVal {
            get {
                return this.endWithValField;
            }
            set {
                this.endWithValField = value;
                this.RaisePropertyChanged("endWithVal");
            }
        }
        
        /// <summary />
        private string endWithAddValField;
        
        /// <remarks/>
        public string endWithAddVal {
            get {
                return this.endWithAddValField;
            }
            set {
                this.endWithAddValField = value;
                this.RaisePropertyChanged("endWithAddVal");
            }
        }
        
        /// <summary />
        private attachTypeEntity endWithAttachTypeField;
        
        /// <remarks/>
        public attachTypeEntity endWithAttachType {
            get {
                return this.endWithAttachTypeField;
            }
            set {
                this.endWithAttachTypeField = value;
                this.RaisePropertyChanged("endWithAttachType");
            }
        }
        
        /// <summary />
        private bool trimField;
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
                this.RaisePropertyChanged("trim");
            }
        }
        
        /// <summary />
        private bool replaceField;
        
        /// <remarks/>
        public bool replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
                this.RaisePropertyChanged("replace");
            }
        }
        
        /// <summary />
        private string findTextField;
        
        /// <remarks/>
        public string findText {
            get {
                return this.findTextField;
            }
            set {
                this.findTextField = value;
                this.RaisePropertyChanged("findText");
            }
        }
        
        /// <summary />
        private string replaceTextField;
        
        /// <remarks/>
        public string replaceText {
            get {
                return this.replaceTextField;
            }
            set {
                this.replaceTextField = value;
                this.RaisePropertyChanged("replaceText");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ResultActionEntitySubstringType {
        
        /// <remarks/>
        simple,
        
        /// <remarks/>
        fromTo,
        
        /// <remarks/>
        search,
        
        /// <remarks/>
        searchTo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class attachTypeEntity : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private attachTypeEntityAttachType attachTypeField;
        
        /// <remarks/>
        public attachTypeEntityAttachType attachType {
            get {
                return this.attachTypeField;
            }
            set {
                this.attachTypeField = value;
                this.RaisePropertyChanged("attachType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum attachTypeEntityAttachType {
        
        /// <remarks/>
        before,
        
        /// <remarks/>
        after,
        
        /// <remarks/>
        both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum xpathEntityGetType {
        
        /// <remarks/>
        attribute,
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        html,
        
        /// <remarks/>
        singleNode,
        
        /// <remarks/>
        nodeCollection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum xpathEntityFindType {
        
        /// <remarks/>
        inputData,
        
        /// <remarks/>
        getUrl,
        
        /// <remarks/>
        previusRule,
        
        /// <remarks/>
        previusXpath,
        
        /// <remarks/>
        pageLoop,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum xpathEntityInputCollectionType {
        
        /// <remarks/>
        singleNode,
        
        /// <remarks/>
        nodeCollection,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ConvertActionEntity : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool convertToFormatField;
        
        /// <remarks/>
        public bool convertToFormat {
            get {
                return this.convertToFormatField;
            }
            set {
                this.convertToFormatField = value;
                this.RaisePropertyChanged("convertToFormat");
            }
        }
        
        /// <summary />
        private string toFormatField;
        
        /// <remarks/>
        public string toFormat {
            get {
                return this.toFormatField;
            }
            set {
                this.toFormatField = value;
                this.RaisePropertyChanged("toFormat");
            }
        }
        
        /// <summary />
        private bool changeSizeField;
        
        /// <remarks/>
        public bool changeSize {
            get {
                return this.changeSizeField;
            }
            set {
                this.changeSizeField = value;
                this.RaisePropertyChanged("changeSize");
            }
        }
        
        /// <summary />
        private int toSizewField;
        
        /// <remarks/>
        public int toSizew {
            get {
                return this.toSizewField;
            }
            set {
                this.toSizewField = value;
                this.RaisePropertyChanged("toSizew");
            }
        }
        
        /// <summary />
        private int toSizeHField;
        
        /// <remarks/>
        public int toSizeH {
            get {
                return this.toSizeHField;
            }
            set {
                this.toSizeHField = value;
                this.RaisePropertyChanged("toSizeH");
            }
        }
        
        /// <summary />
        private bool createThumbsField;
        
        /// <remarks/>
        public bool createThumbs {
            get {
                return this.createThumbsField;
            }
            set {
                this.createThumbsField = value;
                this.RaisePropertyChanged("createThumbs");
            }
        }
        
        /// <summary />
        private ConvertActionEntityThumbs thumbsField;
        
        /// <remarks/>
        public ConvertActionEntityThumbs Thumbs {
            get {
                return this.thumbsField;
            }
            set {
                this.thumbsField = value;
                this.RaisePropertyChanged("Thumbs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ConvertActionEntityThumbs : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private int toSizeHField;
        
        /// <remarks/>
        public int toSizeH {
            get {
                return this.toSizeHField;
            }
            set {
                this.toSizeHField = value;
                this.RaisePropertyChanged("toSizeH");
            }
        }
        
        /// <summary />
        private int toSizeWField;
        
        /// <remarks/>
        public int toSizeW {
            get {
                return this.toSizeWField;
            }
            set {
                this.toSizeWField = value;
                this.RaisePropertyChanged("toSizeW");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class RuleEntity : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string idField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <summary />
        private object fetchedDataField;
        
        /// <remarks/>
        public object fetchedData {
            get {
                return this.fetchedDataField;
            }
            set {
                this.fetchedDataField = value;
                this.RaisePropertyChanged("fetchedData");
            }
        }
        
        /// <summary />
        private string urlField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <summary />
        private string pluginNsNameField;
        
        /// <remarks/>
        public string pluginNsName {
            get {
                return this.pluginNsNameField;
            }
            set {
                this.pluginNsNameField = value;
                this.RaisePropertyChanged("pluginNsName");
            }
        }
        
        /// <summary />
        private string htmlFileNameField;
        
        /// <remarks/>
        public string htmlFileName {
            get {
                return this.htmlFileNameField;
            }
            set {
                this.htmlFileNameField = value;
                this.RaisePropertyChanged("htmlFileName");
            }
        }
        
        /// <summary />
        private httpHeadersCollection customHttpHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customHttpHeader")]
        public httpHeadersCollection customHttpHeader {
            get {
                return this.customHttpHeaderField;
            }
            set {
                this.customHttpHeaderField = value;
                this.RaisePropertyChanged("customHttpHeader");
            }
        }
        
        /// <summary />
        private RuleEntityType typeField;
        
        /// <remarks/>
        public RuleEntityType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private RuleEntityXpath xpathField;
        
        /// <remarks/>
        public RuleEntityXpath xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private ResultActionEntityCollection resultActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResultAction")]
        public ResultActionEntityCollection ResultAction {
            get {
                return this.resultActionField;
            }
            set {
                this.resultActionField = value;
                this.RaisePropertyChanged("ResultAction");
            }
        }
        
        /// <summary />
        private RuleEntityDownloadAction downloadActionField;
        
        /// <remarks/>
        public RuleEntityDownloadAction DownloadAction {
            get {
                return this.downloadActionField;
            }
            set {
                this.downloadActionField = value;
                this.RaisePropertyChanged("DownloadAction");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RuleEntityType {
        
        /// <remarks/>
        httpGet,
        
        /// <remarks/>
        httpPost,
        
        /// <remarks/>
        plugin,
        
        /// <remarks/>
        xpath,
        
        /// <remarks/>
        download,
        
        /// <remarks/>
        loadHtmlFromfile,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RuleEntityXpath : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private RuleEntityXpathType typeField;
        
        /// <remarks/>
        public RuleEntityXpathType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private xpathEntityCollection xpathRuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("xpathRule")]
        public xpathEntityCollection xpathRule {
            get {
                return this.xpathRuleField;
            }
            set {
                this.xpathRuleField = value;
                this.RaisePropertyChanged("xpathRule");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RuleEntityXpathType {
        
        /// <remarks/>
        single,
        
        /// <remarks/>
        collection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RuleEntityDownloadAction : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private ConvertActionEntity convertActionField;
        
        /// <remarks/>
        public ConvertActionEntity ConvertAction {
            get {
                return this.convertActionField;
            }
            set {
                this.convertActionField = value;
                this.RaisePropertyChanged("ConvertAction");
            }
        }
        
        /// <summary />
        private RuleEntityDownloadActionDirSaveToFileInfo dirSaveToFileInfoField;
        
        /// <remarks/>
        public RuleEntityDownloadActionDirSaveToFileInfo DirSaveToFileInfo {
            get {
                return this.dirSaveToFileInfoField;
            }
            set {
                this.dirSaveToFileInfoField = value;
                this.RaisePropertyChanged("DirSaveToFileInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RuleEntityDownloadActionDirSaveToFileInfo : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string startFolderField;
        
        /// <remarks/>
        public string startFolder {
            get {
                return this.startFolderField;
            }
            set {
                this.startFolderField = value;
                this.RaisePropertyChanged("startFolder");
            }
        }
        
        /// <summary />
        private string generateSubFolderField;
        
        /// <remarks/>
        public string generateSubFolder {
            get {
                return this.generateSubFolderField;
            }
            set {
                this.generateSubFolderField = value;
                this.RaisePropertyChanged("generateSubFolder");
            }
        }
        
        /// <summary />
        private string subFolderCustomNameField;
        
        /// <remarks/>
        public string SubFolderCustomName {
            get {
                return this.subFolderCustomNameField;
            }
            set {
                this.subFolderCustomNameField = value;
                this.RaisePropertyChanged("SubFolderCustomName");
            }
        }
        
        /// <summary />
        private RuleEntityDownloadActionDirSaveToFileInfoSubfolderNameType subfolderNameTypeField;
        
        /// <remarks/>
        public RuleEntityDownloadActionDirSaveToFileInfoSubfolderNameType subfolderNameType {
            get {
                return this.subfolderNameTypeField;
            }
            set {
                this.subfolderNameTypeField = value;
                this.RaisePropertyChanged("subfolderNameType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RuleEntityDownloadActionDirSaveToFileInfoSubfolderNameType {
        
        /// <remarks/>
        yymmdd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("yy/mmdd")]
        yymmdd1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("yy/mm/dd")]
        yymmdd2,
        
        /// <remarks/>
        custom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettingsOnError : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperSettingsOnErrorAction actionField;
        
        /// <remarks/>
        public intelliScraperSettingsOnErrorAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <summary />
        private int repeatTimesField;
        
        /// <remarks/>
        public int repeatTimes {
            get {
                return this.repeatTimesField;
            }
            set {
                this.repeatTimesField = value;
                this.RaisePropertyChanged("repeatTimes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum intelliScraperSettingsOnErrorAction {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        log,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettingsPageLoopInfo : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string urlFormatField;
        
        /// <remarks/>
        public string urlFormat {
            get {
                return this.urlFormatField;
            }
            set {
                this.urlFormatField = value;
                this.RaisePropertyChanged("urlFormat");
            }
        }
        
        /// <summary />
        private string fetchHtmlField;
        
        /// <remarks/>
        public string fetchHtml {
            get {
                return this.fetchHtmlField;
            }
            set {
                this.fetchHtmlField = value;
                this.RaisePropertyChanged("fetchHtml");
            }
        }
        
        /// <summary />
        private string urlSearcherField;
        
        /// <remarks/>
        public string urlSearcher {
            get {
                return this.urlSearcherField;
            }
            set {
                this.urlSearcherField = value;
                this.RaisePropertyChanged("urlSearcher");
            }
        }
        
        /// <summary />
        private string ruleId_getEndPageField;
        
        /// <remarks/>
        public string ruleId_getEndPage {
            get {
                return this.ruleId_getEndPageField;
            }
            set {
                this.ruleId_getEndPageField = value;
                this.RaisePropertyChanged("ruleId_getEndPage");
            }
        }
        
        /// <summary />
        private string[] ruleId_executePageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleId_executePage")]
        public string[] ruleId_executePage {
            get {
                return this.ruleId_executePageField;
            }
            set {
                this.ruleId_executePageField = value;
                this.RaisePropertyChanged("ruleId_executePage");
            }
        }
        
        /// <summary />
        private int startField;
        
        /// <remarks/>
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <summary />
        private int endField;
        
        /// <remarks/>
        public int end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }
        
        /// <summary />
        private string appendBeforePageNumberField;
        
        /// <remarks/>
        public string appendBeforePageNumber {
            get {
                return this.appendBeforePageNumberField;
            }
            set {
                this.appendBeforePageNumberField = value;
                this.RaisePropertyChanged("appendBeforePageNumber");
            }
        }
        
        /// <summary />
        private string appendAfterPageNumberField;
        
        /// <remarks/>
        public string appendAfterPageNumber {
            get {
                return this.appendAfterPageNumberField;
            }
            set {
                this.appendAfterPageNumberField = value;
                this.RaisePropertyChanged("appendAfterPageNumber");
            }
        }
        
        /// <summary />
        private httpHeadersCollection customHttpHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customHttpHeader")]
        public httpHeadersCollection customHttpHeader {
            get {
                return this.customHttpHeaderField;
            }
            set {
                this.customHttpHeaderField = value;
                this.RaisePropertyChanged("customHttpHeader");
            }
        }
        
        /// <summary />
        private intelliScraperSettingsPageLoopInfoPageLoopType pageLoopTypeField;
        
        /// <remarks/>
        public intelliScraperSettingsPageLoopInfoPageLoopType pageLoopType {
            get {
                return this.pageLoopTypeField;
            }
            set {
                this.pageLoopTypeField = value;
                this.RaisePropertyChanged("pageLoopType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum intelliScraperSettingsPageLoopInfoPageLoopType {
        
        /// <remarks/>
        fromStart,
        
        /// <remarks/>
        fromZero_to_byRule,
        
        /// <remarks/>
        fromCustom_to_byRule,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfo : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private intelliScraperStoreInfoType typeField;
        
        /// <remarks/>
        public intelliScraperStoreInfoType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string connectionField;
        
        /// <remarks/>
        public string connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
                this.RaisePropertyChanged("connection");
            }
        }
        
        /// <summary />
        private string csvHeaderField;
        
        /// <remarks/>
        public string csvHeader {
            get {
                return this.csvHeaderField;
            }
            set {
                this.csvHeaderField = value;
                this.RaisePropertyChanged("csvHeader");
            }
        }
        
        /// <summary />
        private string csvFileSaveToField;
        
        /// <remarks/>
        public string csvFileSaveTo {
            get {
                return this.csvFileSaveToField;
            }
            set {
                this.csvFileSaveToField = value;
                this.RaisePropertyChanged("csvFileSaveTo");
            }
        }
        
        /// <summary />
        private bool csvFileClearField;
        
        /// <remarks/>
        public bool csvFileClear {
            get {
                return this.csvFileClearField;
            }
            set {
                this.csvFileClearField = value;
                this.RaisePropertyChanged("csvFileClear");
            }
        }
        
        /// <summary />
        private string csvSeparatorField;
        
        /// <remarks/>
        public string csvSeparator {
            get {
                return this.csvSeparatorField;
            }
            set {
                this.csvSeparatorField = value;
                this.RaisePropertyChanged("csvSeparator");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum intelliScraperStoreInfoType {
        
        /// <remarks/>
        myslq,
        
        /// <remarks/>
        mssql,
        
        /// <remarks/>
        csv,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperAction : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private RuleEntity ruleField;
        
        /// <remarks/>
        public RuleEntity Rule {
            get {
                return this.ruleField;
            }
            set {
                this.ruleField = value;
                this.RaisePropertyChanged("Rule");
            }
        }
        
        /// <summary />
        private SaveEntity saveField;
        
        /// <remarks/>
        public SaveEntity Save {
            get {
                return this.saveField;
            }
            set {
                this.saveField = value;
                this.RaisePropertyChanged("Save");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperActionCollection : System.Collections.Generic.List<intelliScraperAction> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class httpHeadersCollection : System.Collections.Generic.List<httpHeaders> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class SaveEntityMapCollection : System.Collections.Generic.List<SaveEntityMap> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class ResultActionEntityCollection : System.Collections.Generic.List<ResultActionEntity> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class xpathEntityCollection : System.Collections.Generic.List<xpathEntity> {
    }
}
#pragma warning restore 1591