//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.296
//     Generated on:    12/06/2013 16:28:52
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace IntelliScraper.Xml {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class intelliScraper : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperSettings settingsField;
        
        /// <remarks/>
        public intelliScraperSettings settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
                this.RaisePropertyChanged("settings");
            }
        }
        
        /// <summary />
        private intelliScraperStoreInfoCollection storeInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("storeInfo")]
        public intelliScraperStoreInfoCollection storeInfo {
            get {
                return this.storeInfoField;
            }
            set {
                this.storeInfoField = value;
                this.RaisePropertyChanged("storeInfo");
            }
        }
        
        /// <summary />
        private intelliScraperStepCollection scrapeRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("step", IsNullable=false)]
        public intelliScraperStepCollection scrapeRules {
            get {
                return this.scrapeRulesField;
            }
            set {
                this.scrapeRulesField = value;
                this.RaisePropertyChanged("scrapeRules");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettings : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool useProxyField;
        
        /// <remarks/>
        public bool useProxy {
            get {
                return this.useProxyField;
            }
            set {
                this.useProxyField = value;
                this.RaisePropertyChanged("useProxy");
            }
        }
        
        /// <summary />
        private string proxyFileField;
        
        /// <remarks/>
        public string proxyFile {
            get {
                return this.proxyFileField;
            }
            set {
                this.proxyFileField = value;
                this.RaisePropertyChanged("proxyFile");
            }
        }
        
        /// <summary />
        private string useAlsoLocalIpField;
        
        /// <remarks/>
        public string useAlsoLocalIp {
            get {
                return this.useAlsoLocalIpField;
            }
            set {
                this.useAlsoLocalIpField = value;
                this.RaisePropertyChanged("useAlsoLocalIp");
            }
        }
        
        /// <summary />
        private int waitEachRequestMillisecondsField;
        
        /// <remarks/>
        public int waitEachRequestMilliseconds {
            get {
                return this.waitEachRequestMillisecondsField;
            }
            set {
                this.waitEachRequestMillisecondsField = value;
                this.RaisePropertyChanged("waitEachRequestMilliseconds");
            }
        }
        
        /// <summary />
        private int waitAfterErrorField;
        
        /// <remarks/>
        public int waitAfterError {
            get {
                return this.waitAfterErrorField;
            }
            set {
                this.waitAfterErrorField = value;
                this.RaisePropertyChanged("waitAfterError");
            }
        }
        
        /// <summary />
        private intelliScraperSettingsOnError onErrorField;
        
        /// <remarks/>
        public intelliScraperSettingsOnError onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
                this.RaisePropertyChanged("onError");
            }
        }
        
        /// <summary />
        private string imageFolderDownloadField;
        
        /// <remarks/>
        public string imageFolderDownload {
            get {
                return this.imageFolderDownloadField;
            }
            set {
                this.imageFolderDownloadField = value;
                this.RaisePropertyChanged("imageFolderDownload");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettingsOnError : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string actionField;
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <summary />
        private string timesField;
        
        /// <remarks/>
        public string times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("times");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfo : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string connectionField;
        
        /// <remarks/>
        public string connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
                this.RaisePropertyChanged("connection");
            }
        }
        
        /// <summary />
        private intelliScraperStoreInfoTables tablesField;
        
        /// <remarks/>
        public intelliScraperStoreInfoTables tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
                this.RaisePropertyChanged("tables");
            }
        }
        
        /// <summary />
        private string headerField;
        
        /// <remarks/>
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfoTables : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperStoreInfoTablesTable tableField;
        
        /// <remarks/>
        public intelliScraperStoreInfoTablesTable table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfoTablesTable : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string[] colField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("col")]
        public string[] col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
                this.RaisePropertyChanged("col");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStep : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string idField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <summary />
        private string inputIdField;
        
        /// <remarks/>
        public string inputId {
            get {
                return this.inputIdField;
            }
            set {
                this.inputIdField = value;
                this.RaisePropertyChanged("inputId");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string urlField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <summary />
        private string dataTypeField;
        
        /// <remarks/>
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <summary />
        private string xpathField;
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoop loopField;
        
        /// <remarks/>
        public intelliScraperStepLoop loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
                this.RaisePropertyChanged("loop");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoop : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueCollection loopstepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("getvalue", IsNullable=false)]
        public intelliScraperStepLoopGetvalueCollection loopstep {
            get {
                return this.loopstepField;
            }
            set {
                this.loopstepField = value;
                this.RaisePropertyChanged("loopstep");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalue : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string xpathField;
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string attributeNameField;
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <summary />
        private bool trimField;
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
                this.RaisePropertyChanged("trim");
            }
        }
        
        /// <summary />
        private string substringField;
        
        /// <remarks/>
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
                this.RaisePropertyChanged("substring");
            }
        }
        
        /// <summary />
        private string findTextField;
        
        /// <remarks/>
        public string findText {
            get {
                return this.findTextField;
            }
            set {
                this.findTextField = value;
                this.RaisePropertyChanged("findText");
            }
        }
        
        /// <summary />
        private string replaceTextField;
        
        /// <remarks/>
        public string replaceText {
            get {
                return this.replaceTextField;
            }
            set {
                this.replaceTextField = value;
                this.RaisePropertyChanged("replaceText");
            }
        }
        
        /// <summary />
        private string mapTitleField;
        
        /// <remarks/>
        public string mapTitle {
            get {
                return this.mapTitleField;
            }
            set {
                this.mapTitleField = value;
                this.RaisePropertyChanged("mapTitle");
            }
        }
        
        /// <summary />
        private string mapPositionField;
        
        /// <remarks/>
        public string mapPosition {
            get {
                return this.mapPositionField;
            }
            set {
                this.mapPositionField = value;
                this.RaisePropertyChanged("mapPosition");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueIfStartWith ifStartWithField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueIfStartWith ifStartWith {
            get {
                return this.ifStartWithField;
            }
            set {
                this.ifStartWithField = value;
                this.RaisePropertyChanged("ifStartWith");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueIfEndWith ifEndWithField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueIfEndWith ifEndWith {
            get {
                return this.ifEndWithField;
            }
            set {
                this.ifEndWithField = value;
                this.RaisePropertyChanged("ifEndWith");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepCollection stepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step")]
        public intelliScraperStepLoopGetvalueStepCollection step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
                this.RaisePropertyChanged("step");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueIfStartWith : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <summary />
        private string substringField;
        
        /// <remarks/>
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
                this.RaisePropertyChanged("substring");
            }
        }
        
        /// <summary />
        private string attachBeforeField;
        
        /// <remarks/>
        public string attachBefore {
            get {
                return this.attachBeforeField;
            }
            set {
                this.attachBeforeField = value;
                this.RaisePropertyChanged("attachBefore");
            }
        }
        
        /// <summary />
        private string attachAfterField;
        
        /// <remarks/>
        public string attachAfter {
            get {
                return this.attachAfterField;
            }
            set {
                this.attachAfterField = value;
                this.RaisePropertyChanged("attachAfter");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueIfEndWith : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <summary />
        private string substringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
                this.RaisePropertyChanged("substring");
            }
        }
        
        /// <summary />
        private string attachBeforeField;
        
        /// <remarks/>
        public string attachBefore {
            get {
                return this.attachBeforeField;
            }
            set {
                this.attachBeforeField = value;
                this.RaisePropertyChanged("attachBefore");
            }
        }
        
        /// <summary />
        private string attachAfterField;
        
        /// <remarks/>
        public string attachAfter {
            get {
                return this.attachAfterField;
            }
            set {
                this.attachAfterField = value;
                this.RaisePropertyChanged("attachAfter");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStep : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private float idField;
        
        /// <remarks/>
        public float id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <summary />
        private string inputIdField;
        
        /// <remarks/>
        public string inputId {
            get {
                return this.inputIdField;
            }
            set {
                this.inputIdField = value;
                this.RaisePropertyChanged("inputId");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string urlField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <summary />
        private string urlInputField;
        
        /// <remarks/>
        public string urlInput {
            get {
                return this.urlInputField;
            }
            set {
                this.urlInputField = value;
                this.RaisePropertyChanged("urlInput");
            }
        }
        
        /// <summary />
        private string xpathField;
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoop loopField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoop loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
                this.RaisePropertyChanged("loop");
            }
        }
        
        /// <summary />
        private string storetoField;
        
        /// <remarks/>
        public string storeto {
            get {
                return this.storetoField;
            }
            set {
                this.storetoField = value;
                this.RaisePropertyChanged("storeto");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepTableCollection mappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
        public intelliScraperStepLoopGetvalueStepTableCollection mapping {
            get {
                return this.mappingField;
            }
            set {
                this.mappingField = value;
                this.RaisePropertyChanged("mapping");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoop : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstep loopstepField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstep loopstep {
            get {
                return this.loopstepField;
            }
            set {
                this.loopstepField = value;
                this.RaisePropertyChanged("loopstep");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstep : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepGetvalue getvalueField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepGetvalue getvalue {
            get {
                return this.getvalueField;
            }
            set {
                this.getvalueField = value;
                this.RaisePropertyChanged("getvalue");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImage imageField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImage image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepGetvalue : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string xpathField;
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string attributeNameField;
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <summary />
        private bool trimField;
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
                this.RaisePropertyChanged("trim");
            }
        }
        
        /// <summary />
        private string mapTitleField;
        
        /// <remarks/>
        public string mapTitle {
            get {
                return this.mapTitleField;
            }
            set {
                this.mapTitleField = value;
                this.RaisePropertyChanged("mapTitle");
            }
        }
        
        /// <summary />
        private string mapPositionField;
        
        /// <remarks/>
        public string mapPosition {
            get {
                return this.mapPositionField;
            }
            set {
                this.mapPositionField = value;
                this.RaisePropertyChanged("mapPosition");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImage : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalue getvalueField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalue getvalue {
            get {
                return this.getvalueField;
            }
            set {
                this.getvalueField = value;
                this.RaisePropertyChanged("getvalue");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownload downloadField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownload download {
            get {
                return this.downloadField;
            }
            set {
                this.downloadField = value;
                this.RaisePropertyChanged("download");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalue : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string xpathField;
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
                this.RaisePropertyChanged("xpath");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string attributeNameField;
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <summary />
        private bool trimField;
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
                this.RaisePropertyChanged("trim");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalueIfStartWith ifStartWithField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalueIfStartWith ifStartWith {
            get {
                return this.ifStartWithField;
            }
            set {
                this.ifStartWithField = value;
                this.RaisePropertyChanged("ifStartWith");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalueIfStartWith : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <summary />
        private string substringField;
        
        /// <remarks/>
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
                this.RaisePropertyChanged("substring");
            }
        }
        
        /// <summary />
        private string attachBeforeField;
        
        /// <remarks/>
        public string attachBefore {
            get {
                return this.attachBeforeField;
            }
            set {
                this.attachBeforeField = value;
                this.RaisePropertyChanged("attachBefore");
            }
        }
        
        /// <summary />
        private string attachAfterField;
        
        /// <remarks/>
        public string attachAfter {
            get {
                return this.attachAfterField;
            }
            set {
                this.attachAfterField = value;
                this.RaisePropertyChanged("attachAfter");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownload : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadFolderInfo folderInfoField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadFolderInfo folderInfo {
            get {
                return this.folderInfoField;
            }
            set {
                this.folderInfoField = value;
                this.RaisePropertyChanged("folderInfo");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvert convertField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvert convert {
            get {
                return this.convertField;
            }
            set {
                this.convertField = value;
                this.RaisePropertyChanged("convert");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadFolderInfo : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string startFolderField;
        
        /// <remarks/>
        public string startFolder {
            get {
                return this.startFolderField;
            }
            set {
                this.startFolderField = value;
                this.RaisePropertyChanged("startFolder");
            }
        }
        
        /// <summary />
        private string generateSubFolderField;
        
        /// <remarks/>
        public string generateSubFolder {
            get {
                return this.generateSubFolderField;
            }
            set {
                this.generateSubFolderField = value;
                this.RaisePropertyChanged("generateSubFolder");
            }
        }
        
        /// <summary />
        private string subfolderNameTypeField;
        
        /// <remarks/>
        public string subfolderNameType {
            get {
                return this.subfolderNameTypeField;
            }
            set {
                this.subfolderNameTypeField = value;
                this.RaisePropertyChanged("subfolderNameType");
            }
        }
        
        /// <summary />
        private string subfolderValueNameField;
        
        /// <remarks/>
        public string subfolderValueName {
            get {
                return this.subfolderValueNameField;
            }
            set {
                this.subfolderValueNameField = value;
                this.RaisePropertyChanged("subfolderValueName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvert : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string convertToFormatField;
        
        /// <remarks/>
        public string convertToFormat {
            get {
                return this.convertToFormatField;
            }
            set {
                this.convertToFormatField = value;
                this.RaisePropertyChanged("convertToFormat");
            }
        }
        
        /// <summary />
        private string toFormatField;
        
        /// <remarks/>
        public string toFormat {
            get {
                return this.toFormatField;
            }
            set {
                this.toFormatField = value;
                this.RaisePropertyChanged("toFormat");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbs thumbsField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbs thumbs {
            get {
                return this.thumbsField;
            }
            set {
                this.thumbsField = value;
                this.RaisePropertyChanged("thumbs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbs : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbsThumb thumbField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbsThumb thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
                this.RaisePropertyChanged("thumb");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbsThumb : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string preserveAspectRatioField;
        
        /// <remarks/>
        public string preserveAspectRatio {
            get {
                return this.preserveAspectRatioField;
            }
            set {
                this.preserveAspectRatioField = value;
                this.RaisePropertyChanged("preserveAspectRatio");
            }
        }
        
        /// <summary />
        private string withField;
        
        /// <remarks/>
        public string with {
            get {
                return this.withField;
            }
            set {
                this.withField = value;
                this.RaisePropertyChanged("with");
            }
        }
        
        /// <summary />
        private string heightField;
        
        /// <remarks/>
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTable : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string checkExistField;
        
        /// <remarks/>
        public string checkExist {
            get {
                return this.checkExistField;
            }
            set {
                this.checkExistField = value;
                this.RaisePropertyChanged("checkExist");
            }
        }
        
        /// <summary />
        private string checkExistAttributesField;
        
        /// <remarks/>
        public string checkExistAttributes {
            get {
                return this.checkExistAttributesField;
            }
            set {
                this.checkExistAttributesField = value;
                this.RaisePropertyChanged("checkExistAttributes");
            }
        }
        
        /// <summary />
        private string ifExistField;
        
        /// <remarks/>
        public string IfExist {
            get {
                return this.ifExistField;
            }
            set {
                this.ifExistField = value;
                this.RaisePropertyChanged("IfExist");
            }
        }
        
        /// <summary />
        private string onErrorField;
        
        /// <remarks/>
        public string onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
                this.RaisePropertyChanged("onError");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepTableColCollection colField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("col")]
        public intelliScraperStepLoopGetvalueStepTableColCollection col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
                this.RaisePropertyChanged("col");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepTableLoop loopField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepTableLoop loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
                this.RaisePropertyChanged("loop");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTableCol : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string resultNameField;
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
                this.RaisePropertyChanged("resultName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTableLoop : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string resultNameField;
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
                this.RaisePropertyChanged("resultName");
            }
        }
        
        /// <summary />
        private intelliScraperStepLoopGetvalueStepTableLoopCol colField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepTableLoopCol col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
                this.RaisePropertyChanged("col");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTableLoopCol : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string resultNameField;
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
                this.RaisePropertyChanged("resultName");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperStoreInfoCollection : System.Collections.Generic.List<intelliScraperStoreInfo> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperStepCollection : System.Collections.Generic.List<intelliScraperStep> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperStepLoopGetvalueCollection : System.Collections.Generic.List<intelliScraperStepLoopGetvalue> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperStepLoopGetvalueStepCollection : System.Collections.Generic.List<intelliScraperStepLoopGetvalueStep> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperStepLoopGetvalueStepTableCollection : System.Collections.Generic.List<intelliScraperStepLoopGetvalueStepTable> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class intelliScraperStepLoopGetvalueStepTableColCollection : System.Collections.Generic.List<intelliScraperStepLoopGetvalueStepTableCol> {
    }
}
#pragma warning restore 1591