//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.296
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Codice sorgente generato automaticamente da xsd, versione=4.0.30319.1.
// 
namespace IntelliScraper.Data {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class intelliScraper {
        
        private intelliScraperSettings settingsField;
        
        private intelliScraperStoreInfo[] storeInfoField;
        
        private intelliScraperStep[] scrapeRulesField;
        
        /// <remarks/>
        public intelliScraperSettings settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("storeInfo")]
        public intelliScraperStoreInfo[] storeInfo {
            get {
                return this.storeInfoField;
            }
            set {
                this.storeInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("step", IsNullable=false)]
        public intelliScraperStep[] scrapeRules {
            get {
                return this.scrapeRulesField;
            }
            set {
                this.scrapeRulesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettings {
        
        private bool useProxyField;
        
        private string proxyFileField;
        
        private string useAlsoLocalIpField;
        
        private int waitEachRequestMillisecondsField;
        
        private int waitAfterErrorField;
        
        private intelliScraperSettingsOnError onErrorField;
        
        private string imageFolderDownloadField;
        
        /// <remarks/>
        public bool useProxy {
            get {
                return this.useProxyField;
            }
            set {
                this.useProxyField = value;
            }
        }
        
        /// <remarks/>
        public string proxyFile {
            get {
                return this.proxyFileField;
            }
            set {
                this.proxyFileField = value;
            }
        }
        
        /// <remarks/>
        public string useAlsoLocalIp {
            get {
                return this.useAlsoLocalIpField;
            }
            set {
                this.useAlsoLocalIpField = value;
            }
        }
        
        /// <remarks/>
        public int waitEachRequestMilliseconds {
            get {
                return this.waitEachRequestMillisecondsField;
            }
            set {
                this.waitEachRequestMillisecondsField = value;
            }
        }
        
        /// <remarks/>
        public int waitAfterError {
            get {
                return this.waitAfterErrorField;
            }
            set {
                this.waitAfterErrorField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperSettingsOnError onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
            }
        }
        
        /// <remarks/>
        public string imageFolderDownload {
            get {
                return this.imageFolderDownloadField;
            }
            set {
                this.imageFolderDownloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperSettingsOnError {
        
        private string actionField;
        
        private string timesField;
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfo {
        
        private string nameField;
        
        private string typeField;
        
        private string connectionField;
        
        private intelliScraperStoreInfoTables tablesField;
        
        private string headerField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStoreInfoTables tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfoTables {
        
        private intelliScraperStoreInfoTablesTable tableField;
        
        /// <remarks/>
        public intelliScraperStoreInfoTablesTable table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStoreInfoTablesTable {
        
        private string nameField;
        
        private string[] colField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("col")]
        public string[] col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStep {
        
        private string idField;
        
        private string inputIdField;
        
        private string typeField;
        
        private string urlField;
        
        private string dataTypeField;
        
        private string xpathField;
        
        private intelliScraperStepLoop loopField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string inputId {
            get {
                return this.inputIdField;
            }
            set {
                this.inputIdField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoop loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoop {
        
        private intelliScraperStepLoopGetvalue[] loopstepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("getvalue", IsNullable=false)]
        public intelliScraperStepLoopGetvalue[] loopstep {
            get {
                return this.loopstepField;
            }
            set {
                this.loopstepField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalue {
        
        private string nameField;
        
        private string xpathField;
        
        private string typeField;
        
        private string attributeNameField;
        
        private bool trimField;
        
        private string substringField;
        
        private string findTextField;
        
        private string replaceTextField;
        
        private string mapTitleField;
        
        private string mapPositionField;
        
        private intelliScraperStepLoopGetvalueIfStartWith ifStartWithField;
        
        private intelliScraperStepLoopGetvalueIfEndWith ifEndWithField;
        
        private intelliScraperStepLoopGetvalueStep[] stepField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
            }
        }
        
        /// <remarks/>
        public string findText {
            get {
                return this.findTextField;
            }
            set {
                this.findTextField = value;
            }
        }
        
        /// <remarks/>
        public string replaceText {
            get {
                return this.replaceTextField;
            }
            set {
                this.replaceTextField = value;
            }
        }
        
        /// <remarks/>
        public string mapTitle {
            get {
                return this.mapTitleField;
            }
            set {
                this.mapTitleField = value;
            }
        }
        
        /// <remarks/>
        public string mapPosition {
            get {
                return this.mapPositionField;
            }
            set {
                this.mapPositionField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueIfStartWith ifStartWith {
            get {
                return this.ifStartWithField;
            }
            set {
                this.ifStartWithField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueIfEndWith ifEndWith {
            get {
                return this.ifEndWithField;
            }
            set {
                this.ifEndWithField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step")]
        public intelliScraperStepLoopGetvalueStep[] step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueIfStartWith {
        
        private string valueField;
        
        private string substringField;
        
        private string attachBeforeField;
        
        private string attachAfterField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
            }
        }
        
        /// <remarks/>
        public string attachBefore {
            get {
                return this.attachBeforeField;
            }
            set {
                this.attachBeforeField = value;
            }
        }
        
        /// <remarks/>
        public string attachAfter {
            get {
                return this.attachAfterField;
            }
            set {
                this.attachAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueIfEndWith {
        
        private string valueField;
        
        private string substringField;
        
        private string attachBeforeField;
        
        private string attachAfterField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
            }
        }
        
        /// <remarks/>
        public string attachBefore {
            get {
                return this.attachBeforeField;
            }
            set {
                this.attachBeforeField = value;
            }
        }
        
        /// <remarks/>
        public string attachAfter {
            get {
                return this.attachAfterField;
            }
            set {
                this.attachAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStep {
        
        private float idField;
        
        private string inputIdField;
        
        private string typeField;
        
        private string urlField;
        
        private string urlInputField;
        
        private string xpathField;
        
        private intelliScraperStepLoopGetvalueStepLoop loopField;
        
        private string storetoField;
        
        private intelliScraperStepLoopGetvalueStepTable[] mappingField;
        
        /// <remarks/>
        public float id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string inputId {
            get {
                return this.inputIdField;
            }
            set {
                this.inputIdField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string urlInput {
            get {
                return this.urlInputField;
            }
            set {
                this.urlInputField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoop loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
            }
        }
        
        /// <remarks/>
        public string storeto {
            get {
                return this.storetoField;
            }
            set {
                this.storetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
        public intelliScraperStepLoopGetvalueStepTable[] mapping {
            get {
                return this.mappingField;
            }
            set {
                this.mappingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoop {
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstep loopstepField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstep loopstep {
            get {
                return this.loopstepField;
            }
            set {
                this.loopstepField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstep {
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepGetvalue getvalueField;
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImage imageField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepGetvalue getvalue {
            get {
                return this.getvalueField;
            }
            set {
                this.getvalueField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImage image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepGetvalue {
        
        private string nameField;
        
        private string xpathField;
        
        private string typeField;
        
        private string attributeNameField;
        
        private bool trimField;
        
        private string mapTitleField;
        
        private string mapPositionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public string mapTitle {
            get {
                return this.mapTitleField;
            }
            set {
                this.mapTitleField = value;
            }
        }
        
        /// <remarks/>
        public string mapPosition {
            get {
                return this.mapPositionField;
            }
            set {
                this.mapPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImage {
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalue getvalueField;
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownload downloadField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalue getvalue {
            get {
                return this.getvalueField;
            }
            set {
                this.getvalueField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownload download {
            get {
                return this.downloadField;
            }
            set {
                this.downloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalue {
        
        private string nameField;
        
        private string xpathField;
        
        private string typeField;
        
        private string attributeNameField;
        
        private bool trimField;
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalueIfStartWith ifStartWithField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalueIfStartWith ifStartWith {
            get {
                return this.ifStartWithField;
            }
            set {
                this.ifStartWithField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageGetvalueIfStartWith {
        
        private string valueField;
        
        private string substringField;
        
        private string attachBeforeField;
        
        private string attachAfterField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string substring {
            get {
                return this.substringField;
            }
            set {
                this.substringField = value;
            }
        }
        
        /// <remarks/>
        public string attachBefore {
            get {
                return this.attachBeforeField;
            }
            set {
                this.attachBeforeField = value;
            }
        }
        
        /// <remarks/>
        public string attachAfter {
            get {
                return this.attachAfterField;
            }
            set {
                this.attachAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownload {
        
        private string nameField;
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadFolderInfo folderInfoField;
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvert convertField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadFolderInfo folderInfo {
            get {
                return this.folderInfoField;
            }
            set {
                this.folderInfoField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvert convert {
            get {
                return this.convertField;
            }
            set {
                this.convertField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadFolderInfo {
        
        private string startFolderField;
        
        private string generateSubFolderField;
        
        private string subfolderNameTypeField;
        
        private string subfolderValueNameField;
        
        /// <remarks/>
        public string startFolder {
            get {
                return this.startFolderField;
            }
            set {
                this.startFolderField = value;
            }
        }
        
        /// <remarks/>
        public string generateSubFolder {
            get {
                return this.generateSubFolderField;
            }
            set {
                this.generateSubFolderField = value;
            }
        }
        
        /// <remarks/>
        public string subfolderNameType {
            get {
                return this.subfolderNameTypeField;
            }
            set {
                this.subfolderNameTypeField = value;
            }
        }
        
        /// <remarks/>
        public string subfolderValueName {
            get {
                return this.subfolderValueNameField;
            }
            set {
                this.subfolderValueNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvert {
        
        private string convertToFormatField;
        
        private string toFormatField;
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbs thumbsField;
        
        /// <remarks/>
        public string convertToFormat {
            get {
                return this.convertToFormatField;
            }
            set {
                this.convertToFormatField = value;
            }
        }
        
        /// <remarks/>
        public string toFormat {
            get {
                return this.toFormatField;
            }
            set {
                this.toFormatField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbs thumbs {
            get {
                return this.thumbsField;
            }
            set {
                this.thumbsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbs {
        
        private intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbsThumb thumbField;
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbsThumb thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepLoopLoopstepImageDownloadConvertThumbsThumb {
        
        private string preserveAspectRatioField;
        
        private string withField;
        
        private string heightField;
        
        /// <remarks/>
        public string preserveAspectRatio {
            get {
                return this.preserveAspectRatioField;
            }
            set {
                this.preserveAspectRatioField = value;
            }
        }
        
        /// <remarks/>
        public string with {
            get {
                return this.withField;
            }
            set {
                this.withField = value;
            }
        }
        
        /// <remarks/>
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTable {
        
        private string nameField;
        
        private string checkExistField;
        
        private string checkExistAttributesField;
        
        private string ifExistField;
        
        private string onErrorField;
        
        private intelliScraperStepLoopGetvalueStepTableCol[] colField;
        
        private intelliScraperStepLoopGetvalueStepTableLoop loopField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string checkExist {
            get {
                return this.checkExistField;
            }
            set {
                this.checkExistField = value;
            }
        }
        
        /// <remarks/>
        public string checkExistAttributes {
            get {
                return this.checkExistAttributesField;
            }
            set {
                this.checkExistAttributesField = value;
            }
        }
        
        /// <remarks/>
        public string IfExist {
            get {
                return this.ifExistField;
            }
            set {
                this.ifExistField = value;
            }
        }
        
        /// <remarks/>
        public string onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("col")]
        public intelliScraperStepLoopGetvalueStepTableCol[] col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepTableLoop loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTableCol {
        
        private string nameField;
        
        private string resultNameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTableLoop {
        
        private string resultNameField;
        
        private intelliScraperStepLoopGetvalueStepTableLoopCol colField;
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
            }
        }
        
        /// <remarks/>
        public intelliScraperStepLoopGetvalueStepTableLoopCol col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class intelliScraperStepLoopGetvalueStepTableLoopCol {
        
        private string nameField;
        
        private string resultNameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
            }
        }
    }
}
